version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN:-*}
      - MOCK_API_BASE=${MOCK_API_BASE:-https://ton-mock-railway.up.railway.app}
    restart: unless-stopped
